### ISSUE TITLE
Usecase

### ISSUE THREAD

**Issue by BuiDuc15** [BuiDuc15/Progressive-Web-App_Topic4#2]
Hệ thống bao gồm 1 số các chức năng tổng quát:
- Các chức năng quản lý người dùng: đăng nhập, đăng ký, đổi mật khẩu, quên mật khẩu...
- Tạo set học từ vựng/khái niệm (có thể đính kèm hình ảnh minh họa)
- Có thể chia sẻ các sets học, có thể tìm kiếm sets học của người khác
- Các chức năng ôn tập: nhiều dạng bài ôn tập (trắc nghiệm, tự luận, nối từ...) với khả năng đánh giá tiến độ học (ví dụ: từ nào trả lời đúng nhiều lần rồi thì sẽ không hỏi lại nữa, từ nào hay trả lời sai sẽ xuất hiện lại nhiều lần...)
- Các chức năng kiểm tra: kiểm tra dạng truyền thống (trắc nghiệm + tự luận), kiểm tra kết hợp chơi trò chơi
- Chức năng tạo lớp học: nhóm các sets học vào một lớp, có thể invite người khác hoặc share link cho người khác tự join vào
- Chức năng tạo folder để nhóm các sets học tập: gần giống chức năng tạo lớp học nhưng chỉ có cá nhân sử dụng đượcCông nghệ dự kiến sử dụng: ReactJS + Laravel

**Comment by BuiDuc15** [comment]
Cùng hình dung trong hệ thống gồm các thành phần nào tác động ( actor)

**Comment by CaoTruongSon** [comment]
good

**Comment by toyzz** [comment]
mình sẽ có 3 actor đầu tiên là học viên giáo viên và quản trị viên nhé 
Sau đấy mình sẽ đi vào từng phần riêng để xem nó có thêm những actor nào nữa 
Mỗi 1 yêu cầu thì sẽ cần 1 actor xử lí

**Comment by BuiDuc15** [comment]
Vậy mọi người thống nhất làm 3 cái actor chính trước đã nhé. Người dùng bao gồm những hoạt động chung của cả giáo viên và học viên. T sẽ phân cho từng người tìm hiểu chức năng của từng actor nhé
