### ISSUE TITLE
Actor Người dùng

### ISSUE THREAD

**Issue by BuiDuc15** [BuiDuc15/Progressive-Web-App_Topic4#4]
Liệt kê use case của actor giảng viên/ giáo viên

**Comment by CaoTruongSon** [comment]
theo tui nghĩ người dùng là chung của giáo viên và học viên thì có thể có chức năng như quản lí tài khoản cua mình,đăng ki đăng nhập ,...

**Comment by CaoTruongSon** [comment]
use case của giáo viên thì gồm tạo bài kiểm tra,bài tập,quản lí học viên như tạo bài học, thêm sửa, xoá
,lớp học
use case của học viên thì gồm tạo set học từ vựng,làm bài kiểm tra,bài tập,đăng kí lớp học,tìm kiếm,chia sẻ bài họccủa  giáo viên,vào quản lí lớp học nhưng chỉ học ko thể tạo sửa thêm xoá như giáo viên

**Comment by CaoTruongSon** [comment]
hở người dùng là học viên và giáo vien mà,sao lại chỉ nêu mỗi gv

**Comment by BuiDuc15** [comment]
T ghi nhầm. Use case của gv
