### ISSUE TITLE
Vẽ Usecase 

### ISSUE THREAD

**Issue by BuiDuc15** [BuiDuc15/Progressive-Web-App_Topic4#5]
chịu trách nhiệm vẽ usecase

**Comment by selitalov** [comment]
[PWA tu vung T Use-case.zip](https://github.com/BuiDuc15/Progressive-Web-App_Topic4/files/4424314/PWA.tu.vung.T.Use-case.zip)

**Comment by BuiDuc15** [comment]
![UseCase ver 2](https://user-images.githubusercontent.com/61776302/79933807-3730a480-847b-11ea-87aa-1bec54d46cec.png)
